/-
LMS Foundation - Accumulated Verified Definitions
This file is auto-generated by the LLM Mathematical Society.
Each section was verified by LEAN before being added.

Usage: import LMS.Foundation

=== CHAPTER 4: CATEGORIES (Complete) ===
Verified by: 15x Gemini 3 Flash Preview agents, Generation 1
Artifact: theorem-yoneda_lemma_final_v5-83761ea9
-/

import Mathlib.Tactic.Common
import Mathlib.Logic.Basic
import Mathlib.Logic.Function.Basic
import Mathlib.Logic.Equiv.Defs

universe v u v' u'

namespace LMS.Foundation

/- === 4.2: DEFINE: Category (Tag CH4-CAT) === -/

structure Op (α : Type u) where
  unop : α

structure Category (obj : Type u) : Type (max u (v + 1)) where
  Hom : obj → obj → Type v
  id : (x : obj) → Hom x x
  comp : {x y z : obj} → Hom x y → Hom y z → Hom x z
  id_comp : ∀ {x y : obj} (f : Hom x y), comp (id x) f = f
  comp_id : ∀ {x y : obj} (f : Hom x y), comp f (id y) = f
  assoc : ∀ {x y z w : obj} (f : Hom x y) (g : Hom y z) (h : Hom z w),
    comp (comp f g) h = comp f (comp g h)

/- === 4.2: DEFINE: Opposite Category (Tag CH4-OPPOSITE) === -/

def opposite {obj : Type u} (C : Category.{v, u} obj) : Category (Op obj) where
  Hom x y := C.Hom y.unop x.unop
  id x := C.id x.unop
  comp f g := C.comp g f
  id_comp f := C.comp_id f
  comp_id f := C.id_comp f
  assoc f g h := (C.assoc h g f).symm

/- === 4.2: EXAMPLE: Category of Sets (Tag EX-SET-CAT) === -/

def TypeCat : Category.{v, v+1} (Type v) where
  Hom A B := A → B
  id _ x := x
  comp f g x := g (f x)
  id_comp _ := rfl
  comp_id _ := rfl
  assoc _ _ _ := rfl

/- === 4.2: DEFINE: Functor (Tag CH4-FUNCTOR) === -/

structure Functor {objC : Type u} {objD : Type u'}
  (C : Category.{v, u} objC) (D : Category.{v', u'} objD) where
  obj : objC → objD
  map : {x y : objC} → C.Hom x y → D.Hom (obj x) (obj y)
  map_id : ∀ (x : objC), map (C.id x) = D.id (obj x)
  map_comp : ∀ {x y z : objC} (f : C.Hom x y) (g : C.Hom y z),
    map (C.comp f g) = D.comp (map f) (map g)

/- === 4.2: DEFINE: Natural Transformation (Tag CH4-NATTRANS) === -/

structure NatTrans {objC : Type u} {objD : Type u'}
  {C : Category.{v, u} objC} {D : Category.{v', u'} objD}
  (F G : Functor C D) where
  app : (x : objC) → D.Hom (F.obj x) (G.obj x)
  naturality : ∀ {x y : objC} (f : C.Hom x y),
    D.comp (F.map f) (app y) = D.comp (app x) (G.map f)

theorem NatTrans_ext {objC : Type u} {objD : Type u'}
  {C : Category.{v, u} objC} {D : Category.{v', u'} objD}
  {F G : Functor C D} (η₁ η₂ : NatTrans F G)
  (h : ∀ x, η₁.app x = η₂.app x) : η₁ = η₂ := by
  match η₁, η₂ with
  | ⟨a1, n1⟩, ⟨a2, n2⟩ =>
    congr
    funext x
    exact h x

/- === 4.3: DEFINE: Hom Functor (Tag CH4-HOMFUNCTOR) === -/

def hom_functor {obj : Type u} (C : Category.{v, u} obj) (x : obj) :
  Functor (opposite C) TypeCat.{v} where
  obj y := C.Hom y.unop x
  map f g := C.comp f g
  map_id y := funext (fun g => C.id_comp g)
  map_comp f g := funext (fun h => C.assoc g f h)

/- === 4.3: MILESTONE: Yoneda Lemma (Tag CH4-YONEDA) === -/

def YonedaLemma {obj : Type u} (C : Category.{v, u} obj)
  (F : Functor (opposite C) TypeCat.{v}) (x : obj) :
  (NatTrans (hom_functor C x) F) ≃ (F.obj (Op.mk x)) where
  toFun η := η.app (Op.mk x) (C.id x)
  invFun a := {
    app := fun y f => F.map f a
    naturality := fun {y1 y2} f => funext (fun g => by
      show F.map (C.comp f g) a = (F.map f ∘ F.map g) a
      exact congr_fun (F.map_comp g f) a)
  }
  left_inv η := by
    apply NatTrans_ext
    intro y
    funext f
    dsimp
    let f_op : (opposite C).Hom (Op.mk x) y := f
    have nat := η.naturality f_op
    have nat_val := congr_fun nat (C.id x)
    dsimp [TypeCat, hom_functor, opposite] at nat_val
    rw [C.comp_id] at nat_val
    exact nat_val.symm
  right_inv a := by
    dsimp [TypeCat, opposite]
    exact congr_fun (F.map_id (Op.mk x)) a

/- === 4.3: MILESTONE: Yoneda Embedding is Fully Faithful (Tag CH4-YONEDA-FF) === -/

def YonedaFF {obj : Type u} (C : Category.{v, u} obj) (x y : obj) :
  (C.Hom x y) ≃ (NatTrans (hom_functor C x) (hom_functor C y)) :=
  (YonedaLemma C (hom_functor C y) x).symm

end LMS.Foundation
